import Head from "next/head";
import { useToast, Flex, Text, ModalCloseButton, EnvironmentProvider } from "@chakra-ui/react";
import { useState, useEffect } from "react";
import { ethers } from "ethers";
import Contract from "../../backend/artifacts/contracts/Voting.sol/Voting";
import { useAccount, useProvider, useSigner } from "wagmi";
import Layout from "@/components/Layout/Layout";
import Mainpanel from "@/components/Mainpanel/Mainpanel";

export default function Home() {
  const { address, isConnected } = useAccount();
  const provider = useProvider();
  const toast = useToast();
  const [isOwner, setIsOwner] = useState(false);
  const[phase, setPhase]=useState()

  const account = useAccount({
    onConnect({ address, connector, isReconnected }) {
      console.log("Connected", { address, connector, isReconnected });
    },
  });
  const contractAddress = process.env.NEXT_PUBLIC_SCADDRESS;

  useEffect(() => {
    if (isConnected) {
      checkOwner();
      getStatusOfTheGame();
      toast({
        title: "Connected",
        description:
          "Welcome to my Voting Dapp, you are connected with the address : " +
          address,
        status: "success",
        duration: 5000,
        isClosable: true,
      });
    }
  }, [isConnected]);


  useEffect(() => {
    if (isConnected) {
      checkOwner();
      getStatusOfTheGame();
    }
  }, [address, isConnected]);

  const checkOwner = async () => {
    const contract = await new ethers.Contract(
      contractAddress,
      Contract.abi,
      provider
    );
    let owner = await contract.owner();
    if (address == owner) {
      setIsOwner(true);
    } else {
      setIsOwner(false);
    }
  };

  const getStatusOfTheGame = async() => {
    const contract = await new ethers.Contract(
      contractAddress,
      Contract.abi,
      provider
    );
    const filter = { address: contractAddress, fromBlock: 0 };
    let events = await contract.queryFilter(filter, 0);
    let phase = 0
    events.forEach(event => {
      if (event.event === "WorkflowStatusChange"){       
        phase +=1
      }
    })
    setPhase(phase)
  }

  return (
    <>
      <Head>
        <title>My Voting Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout bg ="#e2e6f7" isOwner={isOwner} phase={phase} setPhase={setPhase}>
        <Mainpanel/>
      </Layout>
    </>
  );
}
